# Generated by Django 5.1.1 on 2024-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_recipe_options_recipe_type_meal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'легкий'), ('MEDIUM', 'средний'), ('HARD', 'сложный'), ('EXPERT', 'эксперт')], max_length=10, null=True, verbose_name='сложность'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_cooking',
            field=models.TimeField(blank=True, null=True, verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type_meal',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'завтрак'), ('LUNCH', 'обед'), ('DINNER', 'ужин'), ('SNACK', 'перекус'), ('BRUNCH', 'бранч'), ('SUPPER', 'поздний ужин'), ('TEA', 'чаепитие'), ('OTHER', 'другое')], max_length=10, null=True, verbose_name='тип приема пищи'),
        ),
    ]
